before_script:
    - source /etc/profile

stages:
    - build

run-build:
    stage: build
    script:
        - dpkg-buildpackage -us -uc 
        - mkdir build
        - mv ../*.deb build/

    artifacts:
        paths:
            - build/*
